version: "3"
services:
  wordpress:
    image: wordpress:5
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.wp_${DOMAINE_NAME}.entrypoints=http"
      - "traefik.http.routers.wp_${DOMAINE_NAME}_https.entrypoints=https"
      - "traefik.http.routers.wp_${DOMAINE_NAME}.rule=Host(`$SOUSDOMAINE_WORDPRESS.$DOMAINE`,`$DOMAINE`)"
      - "traefik.http.routers.wp_${DOMAINE_NAME}_https.rule=Host(`$SOUSDOMAINE_WORDPRESS.$DOMAINE`,`$DOMAINE`)"
      - "traefik.http.middlewares.wp_${DOMAINE_NAME}_redirect.redirectScheme.scheme=https"
      - "traefik.http.routers.wp_${DOMAINE_NAME}.middlewares=wp_${DOMAINE_NAME}_redirect"
      - "traefik.http.routers.wp_${DOMAINE_NAME}_https.tls=true"
      - "traefik.http.routers.wp_${DOMAINE_NAME}_https.tls.certresolver=webresolver"
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
     - ./wp_data:/var/www/html/wp-content
    networks:
      - traefik_network
      - back-end
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    labels:
      - "traefik.enable=false"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ./database/data:/var/lib/mysql
    networks:
      - back-end
networks:
  traefik_network:
    external:
      name: traefik_network
  back-end:
    driver: bridge
